apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: mongoargo
spec:
  type: LoadBalancer
  selector:
    app: springapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
